
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Dilan Lara
 */
public class EjercicioLength2 extends javax.swing.JFrame {

    /**
     * Creates new form EjercicioLength2
     */
    public EjercicioLength2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbltextResult = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        ImagenL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanel1.setBackground(new java.awt.Color(255, 255, 255));
        jpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("LENGTH");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 107, 23));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 204, 255));
        jLabel2.setText("INGRESE SUS CARACTERES");
        jpanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 270, 40));

        lbltextResult.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lbltextResult.setSelectionColor(new java.awt.Color(0, 0, 0));
        lbltextResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbltextResultActionPerformed(evt);
            }
        });
        jpanel1.add(lbltextResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 315, 31));

        jButton1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 204, 255));
        jButton1.setText("Verificar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 118, -1));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 30, 360));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 30, 350));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagen/java4.jpg"))); // NOI18N
        imagen.setText("jLabel3");
        imagen.setPreferredSize(new java.awt.Dimension(30, 40));
        jpanel1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 100, 100));
        jpanel1.add(ImagenL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 210, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String ruta;
    ImageIcon imagen = null;

    int longitud = lbltextResult.getText().length(); // Obtiene la longitud del texto ingresado

    if (longitud <= 10) {
        ruta = switch (longitud) {
            case 1 -> "C:\\Users\\Dilan Lara\\Desktop\\Presentacion_Metodo_length\\src\\com\\imagen\\darwin.jpg";
            case 2 -> "C:\\Users\\Dilan Lara\\Desktop\\Presentacion_Metodo_length\\src\\com\\imagen\\estas seguro.jpeg";
            case 3 -> "C:\\Users\\Dilan Lara\\Desktop\\Presentacion_Metodo_length\\src\\com\\imagen\\conejo.jpg";
            case 4 -> "C:\\Users\\Dilan Lara\\Desktop\\Presentacion_Metodo_length\\src\\com\\imagen\\perrito.jpg";
            case 5 -> "C:\\Users\\Dilan Lara\\Desktop\\Presentacion_Metodo_length\\src\\com\\imagen\\pollo.jpeg";
            case 6 -> "C:\\Users\\Dilan Lara\\Desktop\\Presentacion_Metodo_length\\src\\com\\imagen\\perro1.jpg";
            case 7 -> "C:\\Users\\Dilan Lara\\Desktop\\Presentacion_Metodo_length\\src\\com\\imagen\\random.jpg";
            case 8 -> "C:\\Users\\Dilan Lara\\Desktop\\Presentacion_Metodo_length\\src\\com\\imagen\\patricio.jpeg";
            case 9 -> "C:\\Users\\Dilan Lara\\Desktop\\Presentacion_Metodo_length\\src\\com\\imagen\\imgenc.jpg";
            case 10 -> "C:\\Users\\Dilan Lara\\Desktop\\Presentacion_Metodo_length\\src\\com\\imagen\\jeje.jpg";
            default -> "";
        };

        if (!ruta.isEmpty()) {
            imagen = new ImageIcon(new ImageIcon(ruta).getImage().getScaledInstance(100, 150, Image.SCALE_DEFAULT));
        }

        if (imagen != null) {
            ImagenL.setIcon(imagen);
        }
        
        // Muestra la cantidad de caracteres ingresados en una ventana emergente
    JOptionPane.showMessageDialog(null, "Cantidad de caracteres ingresados: " + longitud);
    lbltextResult.setText("");
    
    } else if (longitud > 10){
        JOptionPane.showMessageDialog(null, "Demasiados caracteres ingresados");
    lbltextResult.setText(""); 
    }

    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbltextResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbltextResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltextResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjercicioLength2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjercicioLength2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjercicioLength2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjercicioLength2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjercicioLength2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenL;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpanel1;
    private javax.swing.JTextField lbltextResult;
    // End of variables declaration//GEN-END:variables
}
